use axum::{
    extract::{Form, State},
    response::{Html, IntoResponse, Response},
};
use crate::{AppState, profile, templates::ProfileTemplate};
use super::forms::ProfileForm;

// GET /profile — file explorer + editor + A4 preview
pub async fn profile_page(
    State(app): State<AppState>,
    axum::extract::Query(params): axum::extract::Query<std::collections::HashMap<String, String>>,
) -> Response {
    let files = profile::list_profile_files().unwrap_or_default();
    let current_file = params.get("file").cloned().unwrap_or_else(|| "index.md".into());
    let content = profile::read_profile_file(&current_file).unwrap_or_default();
    let unlocked = crate::db::get_unlocked_files(&app.db).await.unwrap_or_default();
    let is_locked = !unlocked.contains(&current_file);
    ProfileTemplate { files, current_file, content, is_locked }.into_response()
}

// GET /profile/load?file=... — editor fragment for htmx swap (no full page reload)
pub async fn profile_load(
    State(app): State<AppState>,
    axum::extract::Query(params): axum::extract::Query<std::collections::HashMap<String, String>>,
) -> Response {
    let file = params.get("file").cloned().unwrap_or_else(|| "index.md".into());
    if file.contains("..") {
        return (axum::http::StatusCode::BAD_REQUEST, "Invalid file path").into_response();
    }
    let content = profile::read_profile_file(&file).unwrap_or_default();
    let unlocked = crate::db::get_unlocked_files(&app.db).await.unwrap_or_default();
    let is_locked = !unlocked.contains(&file);
    let esc = |s: &str| s.replace('&', "&amp;").replace('<', "&lt;").replace('"', "&quot;");
    let readonly = if is_locked { r#" readonly"# } else { "" };
    let lock_banner = if is_locked {
        r#"<div id="lock-banner" style="padding:.3rem .6rem;background:var(--surface-alt);border-bottom:1px solid var(--border-subtle);font-size:.8rem;display:flex;align-items:center;gap:.5rem">
  <span style="color:var(--text-secondary)">Locked: this file is auto-generated by AI agents. Manual edits may be overwritten.</span>
  <button onclick="unlockEditor()" style="font-size:.78rem;padding:.15rem .4rem;margin:0">Edit anyway</button>
</div>"#
    } else {
        r#"<div id="lock-banner" style="padding:.3rem .6rem;background:var(--surface-alt);border-bottom:1px solid var(--border-subtle);font-size:.8rem;display:flex;align-items:center;gap:.5rem">
  <span style="color:var(--text-secondary)">Unlocked</span>
  <button onclick="lockEditor()" class="secondary outline" style="font-size:.78rem;padding:.15rem .4rem;margin:0">Lock again</button>
</div>"#
    };
    // ponytail: inline HTML fragment, avoids Askama template parsing issues with # in hx-include
    Html(format!(
        r##"{lock_banner}
<div id="line-numbers"></div>
<textarea id="editor" name="content"{readonly}
          hx-trigger="keyup changed delay:500ms"
          hx-post="/profile" hx-include="{file_field}"
          hx-target="#save-status" hx-swap="innerHTML">{content}</textarea>
<input type="hidden" name="file" value="{file}" id="file-field"
       data-locked="{locked}">"##,
        lock_banner = lock_banner,
        readonly = readonly,
        file_field = "#file-field",
        content = esc(&content),
        file = esc(&file),
        locked = if is_locked { "1" } else { "0" },
    )).into_response()
}

// POST /profile — save edited file to disk
pub async fn profile_save(
    State(_app): State<AppState>,
    Form(body): Form<ProfileForm>,
) -> Response {
    let file = body.file.trim().to_string();
    if file.is_empty() || file.contains("..") {
        return Html("<span style=\"color:var(--status-err)\">Invalid file path.</span>").into_response();
    }
    match profile::write_profile_file(&file, &body.content) {
        Ok(()) => {
            // If index.md was saved, sync to DB too
            if file == "index.md" {
                let _ = profile::sync_profile_to_db(&_app.db).await;
            }
            Html("<span style=\"color:var(--status-ok)\">Saved.</span>").into_response()
        }
        Err(e) => Html(format!("<span style=\"color:var(--status-err)\">Save failed: {}</span>",
            e.to_string().replace('&', "&amp;").replace('<', "&lt;"))).into_response(),
    }
}

// POST /profile/sync — force re-sync profile from files to DB.
pub async fn profile_sync(State(app): State<AppState>) -> Response {
    match profile::sync_profile_to_db(&app.db).await {
        Ok(()) => Html("<span style=\"color:var(--status-ok)\">Profile synced from files.</span>".to_string()).into_response(),
        Err(e) => Html(format!("<span style=\"color:var(--status-err)\">Sync failed: {}</span>",
            e.to_string().replace('&', "&amp;").replace('<', "&lt;"))).into_response(),
    }
}
